[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/ai-skin"
  to = "/public/ai-skin/"
  status = 301

[[redirects]]
  from = "/ai-skin/*"
  to = "/public/ai-skin/:splat"
  status = 200
