[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/ai-skin"
  to = "/public/ai-skin/"
  status = 301

[[redirects]]
  from = "/ai-skin/*"
  to = "/public/ai-skin/:splat"
  status = 200

[[redirects]]
  from = "/campus-agent"
  to = "/public/campus-agent/"
  status = 301

[[redirects]]
  from = "/campus-agent/"
  to = "/public/campus-agent/"
  status = 200

[[redirects]]
  from = "/campus-agent/*"
  to = "/public/campus-agent/:splat"
  status = 200
